import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface ResponseDisplayProps {
  response: string;
  timestamp: string;
}

export default function ResponseDisplay({ response, timestamp }: ResponseDisplayProps) {
  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(response);
      // Could add a toast notification here
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  };

  const formatTimestamp = (timestamp: string) => {
    return new Date(timestamp).toLocaleString();
  };

  return (
    <div className="bg-surface/95 backdrop-blur-sm shadow-2xl rounded-2xl sm:rounded-3xl p-6 sm:p-8 mb-6 fade-in border border-border">
      <div className="flex justify-between items-start mb-6">
        <div className="flex items-center space-x-3">
          <div className="w-3 h-3 bg-gradient-to-r from-green-400 to-emerald-500 rounded-full"></div>
          <div className="text-sm text-text-secondary font-medium">
            AI Response • {formatTimestamp(timestamp)}
          </div>
        </div>
        <button
          onClick={copyToClipboard}
          className="p-2 text-text-secondary hover:text-text-primary hover:bg-border rounded-xl transition-all duration-200 group"
          title="Copy response to clipboard"
        >
          <svg className="w-5 h-5 group-hover:scale-110 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
        </button>
      </div>

      <div className="prose prose-lg max-w-none prose-headings:text-text-primary prose-headings:font-bold prose-p:text-text-secondary prose-p:leading-relaxed prose-li:text-text-secondary prose-li:leading-relaxed prose-strong:text-text-primary prose-strong:font-semibold prose-code:bg-border prose-code:px-2 prose-code:py-1 prose-code:rounded-lg prose-code:text-text-primary prose-code:font-mono prose-code:text-sm prose-pre:bg-surface prose-pre:border prose-pre:border-border prose-pre:rounded-xl prose-pre:p-4 prose-blockquote:border-l-4 prose-blockquote:border-accent prose-blockquote:bg-accent/10 prose-blockquote:p-4 prose-blockquote:rounded-r-lg">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {response}
        </ReactMarkdown>
      </div>

      <div className="mt-6 pt-4 border-t border-border">
        <div className="flex items-center justify-between text-xs text-text-secondary">
          <span>Generated by DeepSeek R1 AI</span>
          <span>Click copy icon to share this response</span>
        </div>
      </div>
    </div>
  );
}